### PR TITLE
updated issue_tracker link

### PR DESCRIPTION
**Pull request by behzodfaiziev**

### CODE REVIEW

**Comment by behzodfaiziev** [comment]
@VB10 i added const and finals to classes. But mistakenly i committed it by `master` branch and it got added into this #94.

**Comment by VB10** [comment]
@behzodfaiziev thank you for contribution <3 there are good point for this version. actually i was remember i fixed final classes but i dont know where it is :)

**Review by yalcin-classlist — APPROVED** [review]
LGTMM

**Review by VB10 — APPROVED** [review]

**Comment by VB10** [comment]
@MehmetKaranlik i was merged these changes.

**Pull request merged**
